<script setup lang="ts">
import { computed, ref } from 'vue'
import { ArrowUpRight, CheckCircle2, ChevronDown, Clock3, Download, Filter, MoreHorizontal, PhoneCall, Plus, RefreshCw, Search, Signal, Users, XCircle } from 'lucide-vue-next'
import { useRoute } from 'vue-router'
const route = useRoute(); const query = ref(''); const callNumber = ref(''); const callBusy = ref(false); const callNotice = ref(''); const activeTab = ref('All calls')
const tabs = ['All calls', 'Missed', 'Outbound', 'Inbound']
const calls = [{ initials: 'MC', name: 'Maya Chen', number: '+1 415 555 0138', direction: 'Inbound', time: '09:42 AM', duration: '04:18', status: 'Connected', color: 'coral' }, { initials: 'LP', name: 'Liam Patel', number: '+1 628 555 0192', direction: 'Outbound', time: '09:18 AM', duration: '02:46', status: 'Connected', color: 'blue' }, { initials: 'EW', name: 'Emma Wilson', number: '+1 510 555 0144', direction: 'Outbound', time: '08:56 AM', duration: '—', status: 'Missed', color: 'gold' }, { initials: 'NO', name: 'Noah Ortiz', number: '+1 415 555 0108', direction: 'Inbound', time: '08:41 AM', duration: '07:12', status: 'Connected', color: 'green' }]
const currentCalls = computed(() => calls.filter((call) => { const tab = activeTab.value === 'All calls' || (activeTab.value === 'Missed' ? call.status === 'Missed' : call.direction === activeTab.value); return tab && `${call.name} ${call.number}`.toLowerCase().includes(query.value.toLowerCase()) }))
const pageCopy = computed(() => ({ '/calls': ['Call activity', 'A living view of the conversations moving through your workspace.'], '/people': ['People & extensions', 'Keep your team reachable with a clear extension directory.'], '/inbound': ['Inbound & IVR', 'Shape how callers find the right person, every time.'], '/trunks': ['SIP trunks', 'Connect your telephony providers and watch their status.'], '/webhooks': ['Webhooks', 'Connect call events to the tools your team already trusts.'], '/health': ['System health', 'A quick read on the services carrying your calls.'], '/settings': ['Settings', 'Workspace preferences and access controls.'] }[route.path] ?? ['Overview', 'Good morning, Jordan. Here is what is happening across your workspace.']))
function startCall() { if (!callNumber.value.trim()) { callNotice.value = 'Enter a phone number or extension first.'; return }; callBusy.value = true; callNotice.value = ''; globalThis.setTimeout(() => { callBusy.value = false; callNotice.value = `Calling ${callNumber.value}...`; callNumber.value = '' }, 520) }
</script>
<template>
  <div class="page-enter"><section class="page-heading"><div><p class="eyebrow">{{ route.path === '/' ? 'Tuesday, September 20, 2026' : 'Workspace' }}</p><h1>{{ pageCopy[0] }}</h1><p class="page-heading__copy">{{ pageCopy[1] }}</p></div><div class="heading-actions"><button class="button button--secondary"><Download :size="15" /> Export</button><button class="button button--primary"><Plus :size="15" /> New configuration</button></div></section>
    <template v-if="route.path === '/'"><section class="signal-banner"><div class="signal-banner__icon"><Signal :size="20" /></div><div><strong>Your calling system is healthy</strong><p>All 12 services are online. Last checked 2 minutes ago.</p></div><button class="icon-button"><RefreshCw :size="16" /></button></section><section class="metric-grid"><article v-for="metric in [{ label: 'Calls today', value: '148', trend: '+12.8%', icon: PhoneCall, tone: 'amber' }, { label: 'Talk time', value: '18h 42m', trend: '+8.4%', icon: Clock3, tone: 'blue' }, { label: 'Missed calls', value: '07', trend: '-4.1%', icon: XCircle, tone: 'coral' }, { label: 'Active users', value: '24 / 28', trend: '85.7%', icon: Users, tone: 'green' }]" :key="metric.label" class="metric-card" :class="`metric-card--${metric.tone}`"><div class="metric-card__top"><span>{{ metric.label }}</span><component :is="metric.icon" :size="17" /></div><strong>{{ metric.value }}</strong><span class="metric-card__trend">{{ metric.trend }} <small>{{ metric.label === 'Active users' ? 'availability' : 'vs yesterday' }}</small></span><div class="progress-track"><i :style="{ width: metric.label === 'Active users' ? '85.7%' : '68%' }" /></div></article></section><section class="dashboard-grid"><article class="surface chart-surface"><div class="surface__header"><div><span class="overline">Volume</span><h2>Call traffic</h2></div><button class="select-button">This week <ChevronDown :size="14" /></button></div><div class="chart-legend"><span><i class="legend-dot legend-dot--amber" />Inbound</span><span><i class="legend-dot legend-dot--blue" />Outbound</span></div><div class="chart"><div class="chart__y"><span>60</span><span>40</span><span>20</span><span>0</span></div><div class="chart__plot"><i class="chart-line chart-line--amber" /><i class="chart-line chart-line--blue" /><div class="chart__grid" /><div class="chart__x"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div></div></article><article class="surface activity-surface"><div class="surface__header"><div><span class="overline">Live feed</span><h2>Recent activity</h2></div><a href="#" class="text-link">View all <ArrowUpRight :size="14" /></a></div><div class="activity-list"><div v-for="item in calls" :key="item.number" class="activity-row"><span class="person-avatar" :class="`person-avatar--${item.color}`">{{ item.initials }}</span><div><strong>{{ item.name }}</strong><p>{{ item.direction }} call · {{ item.time }}</p></div><span class="status-pill" :class="item.status === 'Missed' ? 'status-pill--warn' : 'status-pill--good'">{{ item.status }}</span></div></div></article></section></template>
    <template v-else-if="route.path === '/calls'"><section class="call-bar surface"><div class="call-bar__label"><span class="call-bar__icon"><PhoneCall :size="17" /></span><div><strong>Start a call</strong><small>Dial an extension or external number</small></div></div><div class="call-input"><PhoneCall :size="15" /><input v-model="callNumber" placeholder="Enter number or extension" @keyup.enter="startCall" /><button class="button button--primary" :disabled="callBusy" @click="startCall">{{ callBusy ? 'Calling...' : 'Call' }}</button></div><span v-if="callNotice" class="call-notice">{{ callNotice }}</span></section><section class="surface table-surface"><div class="surface__header table-header"><div><span class="overline">Today</span><h2>Call activity</h2></div><div class="table-tools"><div class="mini-search"><Search :size="15" /><input v-model="query" placeholder="Search calls" /></div><button class="button button--secondary"><Filter :size="15" /> Filters</button></div></div><div class="tabs"><button v-for="tab in tabs" :key="tab" :class="{ 'tab--active': activeTab === tab }" @click="activeTab = tab">{{ tab }}</button></div><div class="table-scroll"><table><thead><tr><th>Contact</th><th>Direction</th><th>Time</th><th>Duration</th><th>Status</th><th /></tr></thead><tbody><tr v-for="call in currentCalls" :key="call.number"><td><div class="table-person"><span class="person-avatar" :class="`person-avatar--${call.color}`">{{ call.initials }}</span><span><strong>{{ call.name }}</strong><small>{{ call.number }}</small></span></div></td><td>{{ call.direction }}</td><td>{{ call.time }}</td><td>{{ call.duration }}</td><td><span class="status-pill" :class="call.status === 'Missed' ? 'status-pill--warn' : 'status-pill--good'">{{ call.status }}</span></td><td><button class="icon-button"><MoreHorizontal :size="17" /></button></td></tr></tbody></table><div v-if="!currentCalls.length" class="empty-state"><Search :size="22" /><strong>No calls found</strong><p>Try a different search or filter.</p></div></div></section></template>
    <template v-else><section class="surface coming-soon"><div class="coming-soon__icon"><CheckCircle2 :size="22" /></div><span class="overline">Workspace module</span><h2>{{ pageCopy[0] }} is ready to connect</h2><p>The shell, permissions, responsive layout, and resource-state patterns are in place. This module will use the backend's tenant-scoped endpoints as they are mapped.</p><button class="button button--secondary"><RefreshCw :size="15" /> Refresh data</button></section></template>
  </div>
</template>
